### ISSUE TITLE
Remove the dependency from custom GeoNode branch

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#183]
The following tasks are required:

- [ ] absorb the DOI field in GeoNode
- [ ] move unesco branch customizations to unesco-ihp GeoNode project (People.recommendation fields, else?)
- [ ] reference GeoNode 2.10.2 instead of custom branch 
- [ ] test

This is a preliminary step for the upgrade to GeoNode 3 (master)
