### ISSUE TITLE
Upgrade IHP-WINS with improved charts and new GN home page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#309]
- [x] test tempaltes with GeoNode upgrade
- [x] integrate the new GN homepage
- [x] integrate improved charts
