### ISSUE TITLE
WP7 [B24] - Autre - Allow import of KML

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#48]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Allow import of KML

**Comment by afabiani** [comment]
I need more details on the expected results/workflow.

**Comment by meyerch** [comment]
Here is a link to download some KML files if needed. The idea is for users to be able to upload not only shapefiles but also kml.

https://www.dropbox.com/sh/82zmlc05aew8nwv/AADEd9AmqhswMvVj-POi1Myaa/KML?dl=0

**Comment by simboss** [comment]
Our plan is to turn this files into real GeoServer layers (optimized as well along the way) so that we can also get printing and maps out of them. We would turn the KML/KMZ into an image + worldfile and then we would internally turn it into an optimize GeoTiff.

This is a little more work that what we plan at the beginning as we were proposing to treat them as a new type of documents but we believe this  would also be a good addition to GeoNode itself.

**Comment by ricardogsilva** [comment]
#### Overview of the work to be done

- The process of uploading a layer into geonode can be divided into two parts:
  1. User imports data files into geonode
      - Layer is created in the geonode database;
      - Basic metadata is extracted;
      - Acess rights are set up;
  1. geonode sends the data to its spatial backend, geoserver
      - data is pre-processed into an appropriate format;
      - data becomes available for visualization/download in a myriad of standards compliant formats.

- The supplied kml sample files have a data type of [kml:GroundOverlay](http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#19). This means that the kml file is accompanied by an image file (png or other) and that it basically carries information necessary to display the image on a geobrowser, such as google earth. As an alternative, the user might also have a kmz file and upload that instead of the kml+image combo. kmz files are simply zip archives that bundle together the kml and image;
- geoserver currently **does not support uploading of kml** files that specify a type of `kml:GroundOverlay`. However, it is possible to extract relevant information from the file and generate a [world file](https://en.wikipedia.org/wiki/World_file). This world file can then be uploaded to geoserver, together with the original image file

  This means that we need to add a pre-processing step after the user uploads the kml (or kmz) to geonode and before starting the geoserver import process.

- When uploading a raster file to geoserver there are a number of other pre-processing operations that should be performed in order to boost the server's performance. The [geoserver importer extension](http://docs.geoserver.org/latest/en/user/extensions/importer/index.html), allows one to set up import pipelines to perform these operations in a streamlined fashion:

  - Convert files to a more suitable format, like GeoTiff
  - Add internal compression and tiling
  - Add overview levels

#### Implementation plan

With this information in mind, I plan to:

- [ ] Change geonode in order to allow uploading of kml+image files;
- [ ] Change geonode in order to allow uploading of kmz file;
- [ ] Adjust geonode code so that it extracts metadata from kml files in order to generate a geonode Layer;
- [ ] Implement a pre-processing step where the kml is converted to a world file;
- [ ] Implement a geoserver importer pipeline that allows sending the image+world file to geoserver;
- [ ] Add conversion to geotiff to the import pipeline;
- [ ] Add internal compression to geotiff to the import pipeline;
- [ ] Add internal tiling to geotiff to the import pipeline;
- [ ] Add internal overviews to geotiff to the import pipeline;

@simboss @afabiani any additional remarks?

**Comment by simboss** [comment]
I would split this in tasks @ricardogsilva .

We might leave out the last 3 for the first step to make sure we stay within estimates.

**Comment by ricardogsilva** [comment]
Work is waiting for review and test at https://github.com/geosolutions-it/geonode/tree/add-kml-raster-support

A PR to geonode official repository has not been made yet because this work is based on @afabiani 's PR which brings [time series support](https://github.com/GeoNode/geonode/pull/3558), which is still pending acceptance.

**Comment by meyerch** [comment]
Dear Ricardo, 
Apologies for the delay in getting back to you. I will review the ompleted tasks today and leave comments/questions if any in the threads.
Once again, sorry for the lack of response

**Comment by meyerch** [comment]
Hi, 
I have uploaded a .kml file and it seems to be working fine: http://ihp-wins-dev.geo-solutions.it/layers/geonode:CSR5r3_annual0 
 
My only question is how to have the legend show up in the dedicated space on WINS? I am not familiar with .kml files so apologize if this a silly question.
Thanks
